### ISSUE TITLE
iptables doesn't work with ubuntu

### ISSUE THREAD

**Issue by subhashdasyam** [ashraf-s9s/clustercheck-iptables#2]
iptables redirection which you posted doesn't work with ubuntu 
can you please help me with ubuntu iptables

**Comment by grenadecx** [comment]
Iptables works just fine on Ubuntu. If you really want more help you will have to describe where it fails.

**Comment by subhashdasyam** [comment]
I am sorry for late reply, they do work it was my router firewall which blocking the requests.

Can close
